name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: brew install automake openssl llvm; autoreconf -if; CC=/usr/local/Cellar/llvm/11.1.0/bin/clang CXX=/usr/local/Cellar/llvm/11.1.0/bin/clang++ ./configure --with-openssl=/usr/local/Cellar/openssl\@1.1/1.1.1j
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
